language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  matrix:
    -

matrix:
  include:
    - php: 5.4
      env:
        - PHPCS=1
  allow_failures:
    - php: 5.4
      env:
        - PHPCS=1
    - php: hhvm

before_install:
  - uname -a
  - date

install: ./.travis.sh

before_script:
  - travis_retry composer self-update
  - travis_retry composer install
  - phpenv rehash

script:
  - if [ "$PHPCS" == 1 ]; then ./vendor/bin/phpcs --standard=psr2 lib/ tests/; exit $?; fi;
  - phpunit -c tests --coverage-text

notifications:
  email: false

